apiVersion: v1
kind: Secret
metadata:
  name: signaltrack-backend-secrets
  labels:
    app.kubernetes.io/name: signaltrack-backend
type: Opaque
stringData:
  DATABASE_URL: "postgres://postgres:postgres@postgres.default.svc.cluster.local:5432/signaltrack"
  TEST_DATABASE_URL: "postgres://postgres:postgres@postgres.default.svc.cluster.local:5432/signaltrack_test"
  S3_ENDPOINT: "http://minio.default.svc.cluster.local:9000"
