apiVersion: v1
kind: Secret
metadata:
  name: {{ include "signaltrack-backend.fullname" . }}-secrets
  labels:
    {{- include "signaltrack-backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secretEnv.DATABASE_URL | quote }}
  TEST_DATABASE_URL: {{ .Values.secretEnv.TEST_DATABASE_URL | quote }}
  S3_ENDPOINT: {{ .Values.secretEnv.S3_ENDPOINT | quote }}
